import { useState } from "react";

// Live Claude-powered insight. Calls the Netlify serverless function at
// /.netlify/functions/insights, which holds the ANTHROPIC_API_KEY server-side
// (the key is NEVER shipped to the browser). On demand only — no cost on page load.
export function AiInsight() {
  const [text, setText] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [done, setDone] = useState(false);

  async function generate() {
    setLoading(true);
    setError("");
    setText("");
    setDone(false);
    try {
      const res = await fetch("/.netlify/functions/insights", { method: "POST" });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error || `Request failed (${res.status})`);
      }
      const data = await res.json();
      setText(data.insight || "No insight returned.");
      setDone(true);
    } catch (e) {
      setError(
        e instanceof Error ? e.message : "Could not reach the insights service.",
      );
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="ai-insight">
      <div className="ai-head">
        <span className="ai-badge">Live AI</span>
        <h4>Executive insight, generated by Claude</h4>
      </div>
      <div className="ai-sub">
        Click to call the Claude API live and summarize this quarter's sample KPIs into
        plain-English executive guidance — the same insights layer I built into the real dashboard.
      </div>
      <div className="ai-body">
        {loading && (
          <span aria-label="Generating">
            <span className="ai-dot" />
            <span className="ai-dot" />
            <span className="ai-dot" />
          </span>
        )}
        {text &&
          text.split("\n").filter(Boolean).map((p, i) => <p key={i}>{p}</p>)}
        {error && <div className="ai-err">⚠ {error}</div>}
      </div>
      <div className="ai-cta">
        <button className="btn dark" onClick={generate} disabled={loading}>
          {loading ? "Analyzing…" : done ? "Regenerate insight ↻" : "Generate insight with Claude →"}
        </button>
      </div>
    </div>
  );
}
